version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  debug-cloud-init:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run:
          name: Profile CPU and memory every 5s (background)
          command: |
            while true; do
              sleep 5
              uptime
              cloud-init status 
              top -b -c -n 1
              echo "======"
            done


workflows:
  build:
    jobs:
      - debug-cloud-init