version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  build:
    docker:
      - image: cimg/android:2022.08.1
    parallelism: 2
    
    working_directory: ~/project

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Collect first logcat log for two hours
          background: true
          command: |
            adb logcat *:I

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: chmod +x ~/project/gradlew
      - run:
          name: Download Dependencies
          command: ~/project/gradlew androidDependencies
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
      - run: adb shell screencap -p /sdcard/screen.png

      - save_cache:
          paths:
            - ~/project/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run: ls /tmp/
      - run: cat /tmp/*.log