version: 2.1
jobs:
  build:
    docker:
      - image: cimg/android:2022.08

    working_directory: ~/project

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Collect logcat log
          background: true
          command: |
            mkdir ~/logcat/
            adb logcat *:I -f ~/logcat/logcat.txt

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: chmod +x ~/project/gradlew
      - run:
          name: Download Dependencies
          command: ~/project/gradlew androidDependencies

      - save_cache:
          paths:
            - ~/project/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run: ls ~/logcat/