version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  build:
    docker:
      - image: cimg/android:2022.08.1

    working_directory: ~/project

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Collect first logcat log for two hours
          background: true
          command: |
            adb logcat *:I & sleep 10s
            circleci-agent step halt
      - run:
          name: Collect second logcat log after two hours
          background: true
          command: |
            sleep 9s
            adb logcat *:I & sleep 10s
            circleci-agent step halt
      - run:
          name: Collect final logcat log after four hours
          background: true
          command: |
            sleep 19s
            tail -f "/var/log/dpkg.log"

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: chmod +x ~/project/gradlew
      - run:
          name: Download Dependencies
          command: ~/project/gradlew androidDependencies

      - save_cache:
          paths:
            - ~/project/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run: ls /tmp/
      - run: cat /tmp/*.log